force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>LI-{0000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Item__c/fields/Food_Order__c.field-meta.xml
<CustomField>
    <fullName>Food_Order__c</fullName>
    <label>Food Order</label>
    <referenceTo>Food_Orders__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OrderLineItemHandler.cls
public class OrderLineItemHandler {

    public static void updateFoodOrderTotal(Map<Id, Order_Line_Item__c> newMap,
                                            Map<Id, Order_Line_Item__c> oldMap,
                                            Boolean isDelete) {
        Set<Id> foodOrderIds = new Set<Id>();

        if(isDelete){
            for(Order_Line_Item__c oldItem : oldMap.values()){
                if(oldItem.Food_Order__c != null)
                    foodOrderIds.add(oldItem.Food_Order__c);
            }
        } else {
            for(Order_Line_Item__c item : newMap.values()){
                if(item.Food_Order__c != null)
                    foodOrderIds.add(item.Food_Order__c);
            }
        }

        FoodOrderService.calculateGrandTotal(foodOrderIds);
    }
}